# Generated by Django 3.1.5 on 2021-01-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210127_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
