# Generated by Django 3.1.5 on 2021-01-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210128_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('about_me', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('institute', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('cv', models.CharField(max_length=300)),
                ('img_url', models.FileField(upload_to='')),
            ],
        ),
    ]
